#!/usr/bin/python3

#This script will take all the ports from the text file containing the ports discovered open and then arrange them in a command seprated format to use with nmap

import sys

if len(sys.argv) < 2:
	print("Usage: ./map <file-containing-ports>")
	sys.exit(0)

str = ''

with open(sys.argv[1]) as file:
	for line in file.readlines():
		str += f"{line.strip()}" + ","

print(str)
